// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInitData() {
  return window['go']['main']['App']['GetInitData']();
}

export function GetSubagentStatus() {
  return window['go']['main']['App']['GetSubagentStatus']();
}

export function GetWindowName() {
  return window['go']['main']['App']['GetWindowName']();
}

export function LoadReasons() {
  return window['go']['main']['App']['LoadReasons']();
}

export function MarkReady() {
  return window['go']['main']['App']['MarkReady']();
}

export function OpenFile(arg1, arg2) {
  return window['go']['main']['App']['OpenFile'](arg1, arg2);
}

export function SaveReason(arg1) {
  return window['go']['main']['App']['SaveReason'](arg1);
}

export function SaveResponse(arg1) {
  return window['go']['main']['App']['SaveResponse'](arg1);
}

export function SaveSubagentFeedback(arg1) {
  return window['go']['main']['App']['SaveSubagentFeedback'](arg1);
}
