// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInitData() {
  return window['go']['main']['App']['GetInitData']();
}

export function SaveResponse(arg1) {
  return window['go']['main']['App']['SaveResponse'](arg1);
}
