// message-page/src/model.ts — 兼容入口
// 模型选择已抽离到 lib/model-selection.ts；保留此导出避免旧引用断裂。
export {
  DEFAULT_MODEL_SCOPE,
  MAX_RECENT_MODELS,
  MESSAGE_PAGE_SCOPE,
  MODEL_SELECTION_SCOPE,
  SUBAGENT_MODEL_SCOPE,
  getAvailableModels,
  modelLabel,
  orderAvailableModelsForPreferences,
  pinnedModelActionOptions,
  parseModelSpec,
  pickModel,
  readLastModel,
  resolveModel,
  resolveConfiguredModel,
  selectModel,
  setCurrentSessionModel,
  writeLastModel,
  readModelPreferences,
  writeModelPreferences,
  pinModel,
  unpinModel,
  recordModelSelection,
  readScopedModelPreferences,
  readSelectedModel,
  writeSelectedModel,
  preferredModelSpec,
  selectScopedDefaultModel,
  withPinnedModel,
  withSelectedModel,
  withRecordedModel,
  withUnpinnedModel,
} from "../../../lib/model-selection.ts";
export type {
  LastModel,
  ModelPreferences,
  ModelSelection,
  ModelSelectionFailureReason,
  ModelSelectionResult,
  PreferredModelSpec,
  ScopedDefaultModelSelectionResult,
  ScopedModelPreferences,
  SelectableModel,
} from "../../../lib/model-selection.ts";
